name: Build

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-gba:
    name: Build (Nintendo gba)
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        export PATH=$DEVKITARM/bin:$DEVKITARM/tools/bin:$PATH
        make -f Makefile
      env:
        DEVKITARM: /opt/devkitpro/devkitARM
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: yolkfolk-legacy.gba
        path: yolkfolk-legacy.gba
        if-no-files-found: error
    - uses: ncipollo/release-action@v1
      if: ${{ github.event_name == 'push' }}
      with:
        artifacts: yolkfolk-legacy.gba
        body: ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Nintendo GBA build (latest commit)
        tag: yolkfolk-legacy-gba_dev
        allowUpdates: true
        artifactErrorsFailBuild: true
        prerelease: true
        replacesArtifacts: true
