name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dispatcher:
    name: Job dispatcher
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    outputs:
      runCxxAnalyzers: ${{ steps.dispatch.outputs.runCxxAnalyzers }}
    steps:
    - uses: actions/github-script@v7
      id: dispatch
      with:
        script: |
          for await (const modifiedFiles of github.paginate.iterator(
              github.rest.pulls.listFiles, {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: ${{ github.event.number }},
              }
          )) {
              if (modifiedFiles.data.some((fileMetadata) =>
                  [/\.c$/, /\.cpp$/, /\.h$/, /CMakeLists\.txt$/].some((pattern) => pattern.test(fileMetadata.filename))
              )) {
                  core.setOutput("runCxxAnalyzers", "YES");
                  break;
              }
          }
  build:
    name: Make
    uses: ./.github/workflows/build.yml
